### PR TITLE
Handling Android RN 0.47 breaking change

### PR DESCRIPTION
**Pull request by bahaa96**
[facebook/react-native@ce6fb33](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)

### CODE REVIEW

**Comment by ponsho** [comment]
Is this going to be merged?

**Comment by bahaa96** [comment]
IDK, but you can patch it manually till it gets merged, or you can also take a look on react-native-maps

**Comment by ponsho** [comment]
Thanks for the suggestion, that's what we are doing now :(
I was looking at react-native-maps, but it looks like that won't work in China

**Comment by bahaa96** [comment]
Brother google covers everywhere

**Comment by bahaa96** [comment]
Any way you could patch this error manually and use it till it gets fixed

**Pull request merged**
